version: '3.8'

services:
  backend:
    container_name: backend
    build: 
      dockerfile: Dockerfile.backend
      context: .
    volumes:
      - ./backend:/usr/local/src
    image: backend:dev  
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile.frontend
      context: .
    volumes: 
      - ./frontend:/usr/local/src
    image: frontend:dev
    command: npm run start
    ports: 
      - 3000:3000
